/**
 * Row shape for inserting into contact_messages table.
 * id and created_at are typically auto-generated by Supabase.
 */
export interface ContactMessageInsert {
  name: string;
  email: string;
  message: string;
}
